upstream app_server {
        server 127.0.0.1:8001;
#unix:/tmp/gunicorn.sock;
    }

server {
	listen   80; ## listen for ipv4
	listen   [::]:80 default ipv6only=on; ## listen for ipv6
	server_name pc81-160.ipb.ac.rs;
	access_log  /var/log/nginx/vamdc.access.log;

	location /static {
	    autoindex on;
	    alias /opt/NodeSoftware-12.07/nodes/ipbdb1/static/;
	}

        location /get_species/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host/get_species;
            proxy_pass http://app_server/get_species/;
            proxy_redirect http://app_server/get_species/ /get_species/;

            gzip on;
            gzip_types       text/plain application/xml text/xml;
            gzip_proxied any;
        }

        location /get_states/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host/get_states;
            proxy_pass http://app_server/get_states/;
            proxy_redirect http://app_server/get_states/ /get_states/;

            gzip on;
            gzip_types       text/plain application/xml text/xml;
            gzip_proxied any;
        }

        location /get_cs_types/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host/get_cs_types;
            proxy_pass http://app_server/get_cs_types/;
            proxy_redirect http://app_server/get_cs_types/ /get_cs_types/;

            gzip on;
            gzip_types       text/plain application/xml text/xml;
            gzip_proxied any;
        }

        location /test/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host/test;
            proxy_pass http://app_server/test/;
            proxy_redirect http://app_server/test/ /test/;

            gzip on;
            gzip_types       text/plain application/xml text/xml;
            gzip_proxied any;
        }

	location = / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host/;
            proxy_pass http://app_server/;
            proxy_redirect http://app_server/ /;

            gzip on;
            gzip_types       text/plain application/xml text/xml;
            gzip_proxied any;
	}

        location /tap/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host/;
            proxy_pass http://app_server/tap/;
            proxy_redirect http://app_server/tap/ /tap/;

            gzip on;
            gzip_types       text/plain application/xml text/xml;
            gzip_proxied any;
        }

	location /admin/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host/;
            proxy_pass http://app_server/admin/;
            proxy_redirect http://app_server/admin/ /admin/;

            gzip on;
            gzip_types       text/plain application/xml text/xml;
            gzip_proxied any;
        }
}
